apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt
  namespace: ci
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - http01:
       ingress:
         name: web-ingress
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: le-crt
  namespace: ci
spec:
  secretName: tls-secret
  issuerRef:
    kind: Issuer
    name: letsencrypt
  commonName: app.cloudgeeks.tk
  dnsNames:
  - app.cloudgeeks.tk
